project:
  type: website

website:
  title: "Geospatial Research Lab"
  navbar:
    left:
      - href: https://geospatialresearchlab.github.io
        text: Home
      - href: materials.qmd
        text: Materials

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



